name: Question / Discussion
description: Ask a question or start a discussion about CinePro Core
title: 'Question: '
labels: ['â“question', 'ðŸ’¬discussion']

body:
    - type: markdown
      attributes:
          value: |-
              Hey There! ðŸ‘‹ Thanks for reaching out to the CinePro Core community!

              Please fill out this template to help us understand your question better.

              > [!TIP]
              > For general discussions, consider using [GitHub Discussions](https://github.com/orgs/cinepro-org/discussions) instead!

    - type: checkboxes
      attributes:
          label: Prerequisites
          description: '**Please check these before submitting:**'
          options:
              - label: I have read the [README.md](https://github.com/cinepro-org/core/blob/main/README.md)
                required: true
              - label: I have checked the [OMSS Framework documentation](https://github.com/omss-spec/framework)
                required: true
              - label: I have checked [CinePro documentation](https://cinepro.mintlify.app)
                required: true
              - label: I have searched existing issues and discussions for similar questions
                required: true

    - type: dropdown
      attributes:
          label: Question Category
          description: What is your question about?
          options:
              - Provider Development
              - Setup & Configuration
              - OMSS Specification
              - API Usage
              - Integration with CineHome
              - Performance & Optimization
              - Contributing to CinePro
              - Other
      validations:
          required: true

    - type: textarea
      attributes:
          label: Your Question
          description: What would you like to know?
          placeholder: 'Ask your question clearly and provide context...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional Context
          description: Add any other context, code examples, or details about your question here.
          placeholder: |-
              <!-- Optional: Include code snippets, links, or additional information -->

              ```typescript
              // Example code if relevant
              ```
          render: markdown
      validations:
          required: false
